### Data Preprocessing

ML알고리즘은 데이터에 기반하고 있기 때문에 어떤 테이터를 입력으로 가지느냐에 따라 결과도 크게 달라질 수 있습니다. (Garbage In Garbage Out)</br>
사이킷런의 ML알고리즘을 적용하기 전에 데이터에 대해 미리 처리해야 할 기본 사항이 있습니다.</br>
* 결손값, 즉 NaN, Null 값은 허용되지 않습니다.
        Null 값은 고정된 다른 값으로 변환해야 합니다.
        Null 값이 얼마 되지 않는다면 피처의 평균값 등으로 간단히 대체할 수 있습니다.
* 사이킷런의 머신러닝 알고리즘은 문자열 값을 입력 값으로 허용하지 않습니다.
        모든 문자열 값은 인코딩되어서 숫자형으로 변환해야 합니다.

#### 데이터 인코딩
머신러닝을 위한 대표적인 인코딩 방식은 레이블 인코딩(Label encoding)과 원-핫 인코딩(One Hot encoding)이 있습니다.
* 레이블 인코딩(Label encoding): 각 칵테고리 피처를 코드형 숫자 값으로 변환하는 것입니다. (ex. 1: 책, 2: 연필, 3: 키보드, 4: 마우스)
* 원 핫 인코딩(One Hot encoding): 피처 값에 따라 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식입니다.

#### 레이블 인코딩(Label Encoding)

In [1]:
# 사이킷런의 LabelEncoder 클래스로 구현합니다.
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform으로 레이블 인코딩 수행.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
# LabelEncoder 객체의 classes_속성 값으로 인코딩 숫자를 확인하면 됩니다.
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


레이블 인코딩은 문자열 값을 숫자형 카테고리 값으로 변환합니다. 굿자의 값의 경우 크고 작음이 작용하기 때문에 특정 ML 알고리즘에서 가중치가 더 부여되거나 더 중요하게 인식할 가능성이 있습니다.</br>
이러한 특성 때문에 레이블 인코딩은 선형회귀와 같은 Ml 알고리즘에서 적용하지 않아야합니다.</br>
트리 계열의 Ml 알고리즘은 이를 반영하지 않으므로 레이블 인코딩도 별 문제가 없습니다.

#### 원-핫 인코딩(One-Hot Encoding)

In [4]:
# 사이킷런에서 OneHotEncoder 클래스로 쉽게 변환이 가능합니다.
# 단, LabelEncoder와 다르게 OneHotEncoder로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환되어야 하며, 입력값으로 2차원의 데이터가 필요합니다.

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [5]:
# 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1, 1)

# 원-핫 인코딩을 적용합니다.

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [6]:
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [7]:
# get_dummies() API를 이용합니다.
# 사이킷런의 OneHotEncoder와 다르게 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환할 수 있습니다.

import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']})

pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        1         0           0         0
6        0         0        1         0           0         0

#### 피터 스케일링과 정규화
서로 다른 변수의 값 버위를 일정한 수준으로 맞추는 작업을 피처 스케일링(feature scaling)이라고 합니다.</br>
대표적인 방법으로 표준화(Standardization)와 정규화(Normalization)가 있습니다.

#### StandardScaler

StandardScaler는 표준화를 쉽게 지원하기 위한 클래스입니다. 개별 피처를 평균이 0이고, 분산이 1인 값으로 변환해줍니다.</br>
가우시안 정규 푼포를 가질 수 있도록 데이터를 변환하는 것은 몇몇 알고리즘에서 매우 중요합니다.</br>
사이킷런의 서포트 벡터 머신(Support Vector Machine), 선형회귀(Linear Regression), 로지스틱회귀(Logistic Regression)는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현되었기 때문에</br>
사전에 표준화를 적용하는 것은 예측 성능 향상에 중요한 요소가 될 수 있습니다.

In [8]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [9]:
# 붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

In [10]:
print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [11]:
# StandardScaler를 이용해 피처를 한번에 표준화합니다.

from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### MinMaxScaler

MinMaxScaler는 데이터 값을 0과 1사이의 범위 값으로 변환합니다. (음수 값이 있으면 -1에서 1으로 변환합니다.)</br>
데이터의 분포가 가우시안 분포가 아닐 경우에 Min, Max Scaler를 적용해 볼 수 있습니다.

In [12]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 세트 변환 fit()과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### 학습 데이터와 테스트 데이터의 스케일링 변환시 유의점

학습 데이터 세트와 테스트 데이터 세트에 이 fits()과 transform()을 적용할 때 주의가 필요합니다.</br>
Scaler 객체를 이용해 학습 데이터 세트로 fit()과 transform()을 적용하면테스트 데이터 세트로는 다시 fit()을 수행하지 않고 학습 데이터 세트로 fit()을 수행한 결과를 이용해 transform() 변환을 적용해야 합니다. </br>
학습 데이터 세트에 이 fit()과 transform()을 적용할 때 주의가 필요합니다.
Scaler 객체를 이용해 학습 데이터 세트로 fit()과 transform()을 적용하면 테스트 데이터 세트로는 다시 fit()을 수행하지 않고 학습 데이터 세트로 fit()을 수행한 결과를 이용해 transform() 변환을 적용해야 한다는 것입니다.

In [13]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지의 값을 가지는 데이터 세트로 생성합니다.
# Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경합니다.

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [14]:
# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정.
scaler.fit(train_array)

#1/10 scale로 train_array 데이터 변환함. 원본 10 -> 1로 변환됨.
train_scaled = scaler.transform(train_array)

print('원본 train_array: ', np.round(train_array.reshape(-1),2))
print('Scale된 train_array: ', np.round(train_scaled.reshape(-1),2))

원본 train_array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [15]:
# fit()을 호출해 스케일링 기준 정보를 다시 적요한 뒤 transform()을 수행합니다.

# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됩니다.
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환함. 원본 5 -> 1로 변환.
test_scaled = scaler.transform(test_array)

# test_array의 scale 변환 출력
print('원본 test_array: ', np.round(test_array.reshape(-1),2))
print('Scaled 된 test: ', np.round(test_scaled.reshape(-1),2))

원본 test_array:  [0 1 2 3 4 5]
Scaled 된 test:  [0.  0.2 0.4 0.6 0.8 1. ]


머신러닝 모델은 학습 데이터를 기반으로 학습되기 때문에 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 하며, 테스트 데이터의 1값은 학습 데이터와 동일하게 0 또는 1 값으로 변환되어야 합니다.</br>
따라서 테스트 데이터에 다시 fit()을 적용해서는 안되며 학습 데이터이미 fit()이 적용된 Scaler 객체를 이용해 transform()으로 변환해야 합니다.

In [16]:
# 테스트 데이터에 fit()을 호출하지 않고 학습 데이터로 fit()을 수행한 MinMaxScaler 객체의 transform)을 이용해 데이터를 변환합니다.

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array: ', np.round(train_array.reshape(-1), 2))
print('Scale 된 train_array', np.round(train_scaled.reshape(-1),2))

원본 train_array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Scale 된 train_array [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [17]:
#test array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print('\n원본 test_array: ', np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터: ', np.round(test_scaled.reshape(-1),2))


원본 test_array:  [0 1 2 3 4 5]
Scale된 test_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5]


##### <요약>
* 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
* 여의치 않다면 테스트 데이터 변환시에는 fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 Scaler 객체를 이용해 transform()으로 변환